# Generated by Django 4.1.7 on 2023-03-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_alter_progress_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
